### ISSUE TITLE
readme/install/usage

### ISSUE THREAD

**Issue by valexa** [utensil/lol-model-format#1]
There is so much stuff in there from format specs to quake models, please give us some details about which is your code and how to run it, i assume it is ruby and the whole project is a ruby gem ?

Please give instruction how to convert a skn to dae for example, i would expect something like: 

/usr/bin/ruby /lol-model-format-master/spec/skn_file_spec.rb /DATA/Characters/Annie/Annie.skn Annie.dae

**Comment by utensil** [comment]
The project is not a ruby gem, yet. The project is an attempt to implement the conversion but it's only partially functional, for example, it can only convert the static part of the models but not the animations.

There is currently no command line interface, yet, because it's not complete. 

Specs are can be run by ruby gem `rspec`, which is a well-known BDD testing tool. You may also run `rake`, because I've written a Rakefile for  Travis CI.

The project, as in its current status, can only be a reference implementation for other programmers who wanna implement a LOL model converter or viewer, but not usable for end users. If you are not planning to dig into the codes(which aren't too many), then this project, as for now, probably doesn't suit your need.

For end users, I would recommend http://code.google.com/p/lolmodelviewer/  which I cloned and modified a little bit as https://github.com/utensil/lolmodelviewer and it's a C# project. And if you just want to view models outside of the game, you may try http://www.lolking.net/models which is online and really cool.

**Comment by matrix3d** [comment]
the just static.
the animations part are more useful vs the static part.
